name: Build DesmumePSP
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches:
      - main
      - hle
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with pspdev/pspdev Docker image
        run: |
          # Execute make in the /src/build directory within the container
          docker run --rm -v "$PWD:/src" pspdev/pspdev:latest make -C /src/build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: psp-homebrew
          path: |
            build/EBOOT.PBP
            build/*.prx
            build/*.elf